// src/mockData/orderRequests.ts
import type { OrderRequest } from "../types";

export const orderRequestsSeed: OrderRequest[] = [
  {
    id: "REQ-3001",
    requester: "Nicolas",
    client: "Vietnam Importer A",
    consignee: "VIETNAM IMPORTER A CO., LTD.",
    notify: "VIETNAM IMPORTER A - LOGISTICS",
    incoterm: "CFR",
    destination: "HCMC, Vietnam",
    shipmentEtdMonth: "2026-01",
    paymentMethod: "Payment Against Docs",
    certifications: ["N/A"],
    inspection: true,
    shippingInstructionsStatus: "PENDIENTE",
    additionalLabel: "NO",
    additionalRequirements: "25-26-27-28 Kg carton, Marine Farm Logo",
    items: [
      {
        product: "Coho HG IQF",
        quality: "Premium",
        size: "9 lbs Up",
        price: { value: 6.8, uom: "kg" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3002",
    requester: "Nicolas",
    client: "Thai Distributor A",
    consignee: "THAI DISTRIBUTOR A CO., LTD.",
    notify: "THAI DISTRIBUTOR A - IMPORT",
    incoterm: "CFR",
    destination: "Bangkok, Thailand",
    shipmentEtdMonth: "2026-02",
    paymentMethod: "T/T 30% advance, 70% against docs",
    certifications: ["ASC"],
    inspection: false,
    shippingInstructionsStatus: "OK",
    additionalLabel: "NO",
    additionalRequirements: "Master carton 25 kg, frozen, English/Thai label",
    items: [
      {
        product: "Atlantic HON",
        quality: "Premium",
        size: "6-7",
        price: { value: 2.55, uom: "lb" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3003",
    requester: "Nicolas",
    client: "China Trader A",
    consignee: "CHINA TRADER A (SHANGHAI)",
    notify: "CHINA TRADER A - DOCS",
    incoterm: "CFR",
    destination: "Shanghai, China",
    shipmentEtdMonth: "2026-03",
    paymentMethod: "LC at sight",
    certifications: ["BAP4"],
    inspection: true,
    shippingInstructionsStatus: "PENDIENTE",
    additionalLabel: "YES",
    additionalRequirements: "Chinese label, 20kg master carton",
    items: [
      {
        product: "Atlantic HON",
        quality: "Premium",
        size: "7-8",
        price: { value: 2.45, uom: "lb" },
        volume: { value: 12000, uom: "kg" },
      },
      {
        product: "Atlantic HON",
        quality: "Premium",
        size: "6-7",
        price: { value: 2.39, uom: "lb" },
        volume: { value: 8000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3004",
    requester: "Nicolas",
    client: "Dongwon",
    consignee: "DONGWON F&B",
    notify: "DONGWON - IMPORT TEAM",
    incoterm: "CFR",
    destination: "Busan, Korea",
    shipmentEtdMonth: "2026-01",
    paymentMethod: "Payment Against Docs",
    certifications: ["ASC", "BAP4"],
    inspection: true,
    shippingInstructionsStatus: "OK",
    additionalLabel: "NO",
    additionalRequirements: "Korean label, 10kg cartons",
    items: [
      {
        product: "Coho HG IQF",
        quality: "Premium",
        size: "9 Up",
        price: { value: 6.2, uom: "kg" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3005",
    requester: "Nicolas",
    client: "CJ Freshway",
    consignee: "CJ FRESHWAY",
    notify: "CJ - DOCS TEAM",
    incoterm: "CFR",
    destination: "Incheon, Korea",
    shipmentEtdMonth: "2025-12",
    paymentMethod: "Payment Against Docs",
    certifications: ["ASC"],
    inspection: true,
    shippingInstructionsStatus: "PENDIENTE",
    additionalLabel: "NO",
    additionalRequirements: "Korean label, 15kg master carton",
    items: [
      {
        product: "Coho HG IQF",
        quality: "Premium",
        size: "8-9 lbs",
        price: { value: 6.35, uom: "kg" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "BORRADOR",
  },
  {
    id: "REQ-3006",
    requester: "Nicolas",
    client: "Minute Gourmet",
    consignee: "MINUTE GOURMET INC.",
    notify: "GERALD EGASSE / DOCS",
    incoterm: "CFR",
    destination: "Manila, Philippines",
    shipmentEtdMonth: "2026-02",
    paymentMethod: "Payment Against Docs",
    certifications: ["ABF"],
    inspection: false,
    shippingInstructionsStatus: "OK",
    additionalLabel: "NO",
    additionalRequirements: "25kg master carton, logo Marine Farm",
    items: [
      {
        product: "Coho HON IQF",
        quality: "Premium",
        size: "10 Up",
        price: { value: 6.9, uom: "kg" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3007",
    requester: "Nicolas",
    client: "Singapore Importer A",
    consignee: "SG IMPORTER A PTE LTD",
    notify: "SG IMPORTER A - OPS",
    incoterm: "CFR",
    destination: "Singapore",
    shipmentEtdMonth: "2026-01",
    paymentMethod: "T/T 100% against docs",
    certifications: ["N/A"],
    inspection: true,
    shippingInstructionsStatus: "PENDIENTE",
    additionalLabel: "YES",
    additionalRequirements: "English label, 20kg master carton",
    items: [
      {
        product: "Coho HG IQF",
        quality: "Premium",
        size: "10 lbs Up",
        price: { value: 3.15, uom: "lb" },
        volume: { value: 18000, uom: "kg" },
      },
    ],
    status: "BORRADOR",
  },
  {
    id: "REQ-3008",
    requester: "Nicolas",
    client: "Malaysia Importer A",
    consignee: "MY IMPORTER A SDN BHD",
    notify: "MY IMPORTER A - FINANCE",
    incoterm: "CFR",
    destination: "Port Klang, Malaysia",
    shipmentEtdMonth: "2026-03",
    paymentMethod: "LC 60 days",
    certifications: ["BAP4"],
    inspection: false,
    shippingInstructionsStatus: "OK",
    additionalLabel: "NO",
    additionalRequirements: "25kg carton",
    items: [
      {
        product: "Atlantic HON",
        quality: "Premium",
        size: "7-8",
        price: { value: 2.52, uom: "lb" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3009",
    requester: "Nicolas",
    client: "Vietnam Importer B",
    consignee: "VIETNAM IMPORTER B CO., LTD.",
    notify: "VIETNAM IMPORTER B - DOCS",
    incoterm: "CFR",
    destination: "Hanoi, Vietnam",
    shipmentEtdMonth: "2026-02",
    paymentMethod: "Payment Against Docs",
    certifications: ["ASC", "ABF"],
    inspection: true,
    shippingInstructionsStatus: "PENDIENTE",
    additionalLabel: "NO",
    additionalRequirements: "25kg cartons, mixed sizes allowed",
    items: [
      {
        product: "Atlantic HON",
        quality: "Premium",
        size: "6-7",
        price: { value: 2.42, uom: "lb" },
        volume: { value: 12000, uom: "kg" },
      },
      {
        product: "Atlantic HON",
        quality: "Premium",
        size: "7-8",
        price: { value: 2.48, uom: "lb" },
        volume: { value: 9000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
  {
    id: "REQ-3010",
    requester: "Nicolas",
    client: "China Trader B",
    consignee: "CHINA TRADER B (NINGBO)",
    notify: "CHINA TRADER B - DOCS",
    incoterm: "CFR",
    destination: "Ningbo, China",
    shipmentEtdMonth: "2025-12",
    paymentMethod: "Payment Against Docs",
    certifications: ["ASC", "BAP4", "ABF"],
    inspection: true,
    shippingInstructionsStatus: "OK",
    additionalLabel: "YES",
    additionalRequirements: "Chinese label, 20kg master carton",
    items: [
      {
        product: "Coho HG IQF",
        quality: "Premium",
        size: "9 Up",
        price: { value: 6.15, uom: "kg" },
        volume: { value: 20000, uom: "kg" },
      },
    ],
    status: "ENVIADA",
  },
];
